Update Syntax_test.yaml

diff --git a/.github/workflows/Syntax_test.yaml b/.github/workflows/Syntax_test.yaml
--- a/.github/workflows/Syntax_test.yaml
+++ b/.github/workflows/Syntax_test.yaml
@@ -18,13 +18,22 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install pylint
-    - name: Analysing the code with pylint
+    - name: Analysing the code with pylint and handle errors
       run: |
-        pylint_score=$(pylint --score=y $(git ls-files '*.py') | grep -oP '(?<=Your code has been rated at ).*(?=/10)')
-        echo "Оценка Pylint: $pylint_score"
+        pylint_output=$(pylint $(git ls-files '*.py'))
+        pylint_score=$(echo "$pylint_output" | grep -oP '(?<=Your code has been rated at ).*(?=/10)')
+        
+        if [ -z "$pylint_score" ]; then
+          echo "An error occurred while running pylint. Check the pylint_output for details:"
+          echo "$pylint_output"
+          exit 1
+        fi
+        
+        echo "Pylint Score: $pylint_score"
+        
         if (( $(echo "$pylint_score > 8.5" | bc -l) )); then
-          echo "Проверка прошла успешно!"
+          echo "Check passed successfully!"
         else
-          echo "Пересмотрите код..."
-          exit 1 # Добавляем это, чтобы тест проваливался
+          echo "Please review the code..."
+          exit 1
         fi
